CREATE DATABASE COURSEMANAGEMENT;
USE COURSEMANAGEMENT;

CREATE TABLE DEPARTMENT(
	DEPARTMENTID CHAR(10),
	NAME NVARCHAR(15),
    BUDGET DOUBLE,
    STARTDATE DATE,
	ADMINISTRATOR NVARCHAR(155),
    PRIMARY KEY (DEPARTMENTID)
);

CREATE TABLE PERSON(
	PERSONID CHAR(10),
	LASTNAME NVARCHAR(55),
    FIRSTNAME NVARCHAR(55),
    HIREDATE DATE,
    ENROLLMENTDATE DATE,
    PRIMARY KEY (PERSONID)
);

CREATE TABLE OFFICEASSIGNMENT(
	INSTRUCTOR CHAR(10),
    LOCATION NVARCHAR(100),
    TIMESTAMP DATE,
    PRIMARY KEY (INSTRUCTOR),
    FOREIGN KEY (INSTRUCTOR) REFERENCES PERSON(PERSONID)
);

CREATE TABLE COURSE(
	COURSEID CHAR(10),
    TITLE NVARCHAR(55),
    CREDITS NVARCHAR(55),
    DEPARTMENTID CHAR(10),
    PRIMARY KEY (COURSEid),
    FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID)
);

CREATE TABLE COURSEINSTRUCTOR(
	COURSEID CHAR(10),
	PERSONID CHAR(10),
    PRIMARY KEY (COURSEID, PERSONID),
    FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID),
    FOREIGN KEY (PERSONID) REFERENCES PERSON(PERSONID)
);

CREATE TABLE STUDENTGRADE(
	ENROLLMENTID CHAR(10),
	COURSEID CHAR(10),
	STUDENTID CHAR(10),
    GRADE INT,
    PRIMARY KEY (ENROLLMENTID),
    FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID),
    FOREIGN KEY (STUDENTID) REFERENCES PERSON(PERSONID)
);


CREATE TABLE ONLINECOURSE(
	COURSEID CHAR(10),
	URL VARCHAR(1000),
    PRIMARY KEY (COURSEID),
    FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID)
);

CREATE TABLE ONSITECOURSE(
	COURSEID CHAR(10),
	LOCATION NVARCHAR(100),
    DATES DATE,
    TIMES TIME,
    PRIMARY KEY (COURSEID),
     FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID)
);