/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.BUS_Course;
import DAO.DAO_Course;
import DTO.DTO_Course;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Đức Anh
 */
public class GUI_Course extends javax.swing.JFrame {

    private static int pos = 0;
    public BUS_Course bus__course = new BUS_Course();
    public DTO_Course dto__course = new DTO_Course();
    private List<DTO_Course> courses;

    /**
     * Creates new form ManageDepartment
     */
    public GUI_Course() {
        initComponents();

        try {
            listCourse();
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Course.class.getName()).log(Level.SEVERE, null, ex);
        }

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(GUI_Course.this,
                        "Bạn có chắc muốn đóng cửa sổ này không?",
                        "Xác nhận đóng",
                        JOptionPane.YES_NO_OPTION
                );

                if (option == JOptionPane.YES_OPTION) {
                    // Thực hiện các thao tác cần thiết trước khi đóng ứng dụng
                    // Ví dụ: Lưu dữ liệu, đóng kết nối, v.v.

                    // Đóng JFrame
                    dispose();
                    String[] args = null;
                    GUI_ChooseOption.main(args);
                }
            }
        });
    }

    private DefaultTableModel convertCourse(List list_course) {
        String[] columnNames_course = {"Course ID", "Title", "Credits", "Department", "URL", "Location", "Days", "Time"};
        Object[][] data_course = new Object[list_course.size()][columnNames_course.length];
        for (int i = 0; i < list_course.size(); i++) {
            DTO_Course dto__course = (DTO_Course) list_course.get(i);
            data_course[i][0] = dto__course.getCOURSEID();
            data_course[i][1] = dto__course.getTITLE();
            data_course[i][2] = dto__course.getCREDITS();
            data_course[i][3] = dto__course.getDepartment().getNAME();
            data_course[i][4] = dto__course.getURL();
            data_course[i][5] = dto__course.getLOCATION();
            data_course[i][6] = dto__course.getDays();
            data_course[i][7] = dto__course.getTimeString();
        }
        DefaultTableModel model_course = new DefaultTableModel(data_course, columnNames_course);
        return model_course;
    }

    public void listCourse() throws SQLException {
        DataTable_Course.removeAll();
        BUS_Course bus__course = new BUS_Course();
        this.courses = bus__course.getAll();
        DefaultTableModel model_course = convertCourse(this.courses);

        DataTable_Course.setModel(model_course);
        LabelStatus_course.setText("Num Of Course: " + this.courses.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTitle = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        PanelFunction = new javax.swing.JPanel();
        LabelSearch = new javax.swing.JLabel();
        TextFieldSearch_course = new javax.swing.JTextField();
        PanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataTable_Course = new javax.swing.JTable();
        LabelStatus_course = new javax.swing.JLabel();
        ButtonAddOnlineCourse = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonAddOnsiteCourse = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Department");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PanelTitle.setBackground(new java.awt.Color(200, 200, 200));
        PanelTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LabelTitle.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("MANAGE COURSE");
        LabelTitle.setToolTipText("");

        javax.swing.GroupLayout PanelTitleLayout = new javax.swing.GroupLayout(PanelTitle);
        PanelTitle.setLayout(PanelTitleLayout);
        PanelTitleLayout.setHorizontalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelTitle)
                .addGap(458, 458, 458))
        );
        PanelTitleLayout.setVerticalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelFunction.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LabelSearch.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        LabelSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelSearch.setText("Search:");
        LabelSearch.setToolTipText("");

        TextFieldSearch_course.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        TextFieldSearch_course.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TextFieldSearch_course.setToolTipText("");
        TextFieldSearch_course.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldSearch_courseKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelFunctionLayout = new javax.swing.GroupLayout(PanelFunction);
        PanelFunction.setLayout(PanelFunctionLayout);
        PanelFunctionLayout.setHorizontalGroup(
            PanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFunctionLayout.createSequentialGroup()
                .addComponent(LabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextFieldSearch_course)
                .addContainerGap())
        );
        PanelFunctionLayout.setVerticalGroup(
            PanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFunctionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldSearch_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        DataTable_Course.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DataTable_Course.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Title", "Credits", "Department ID"
            }
        ));
        DataTable_Course.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DataTable_Course.setFocusTraversalPolicyProvider(true);
        DataTable_Course.setRowHeight(40);
        DataTable_Course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataTable_CourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DataTable_Course);

        LabelStatus_course.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LabelStatus_course.setText("Status");
        LabelStatus_course.setRequestFocusEnabled(false);

        ButtonAddOnlineCourse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ButtonAddOnlineCourse.setText("Add Online Course");
        ButtonAddOnlineCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddOnlineCourseActionPerformed(evt);
            }
        });

        ButtonEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonAddOnsiteCourse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ButtonAddOnsiteCourse.setText("Add Onsite Course");
        ButtonAddOnsiteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddOnsiteCourseActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTableLayout = new javax.swing.GroupLayout(PanelTable);
        PanelTable.setLayout(PanelTableLayout);
        PanelTableLayout.setHorizontalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LabelStatus_course)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addComponent(ButtonAddOnlineCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonAddOnsiteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        PanelTableLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonAddOnlineCourse, ButtonAddOnsiteCourse, ButtonEdit, btnDelete});

        PanelTableLayout.setVerticalGroup(
            PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAddOnlineCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAddOnsiteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelStatus_course)
                .addGap(0, 0, 0))
        );

        PanelTableLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonAddOnlineCourse, ButtonAddOnsiteCourse, ButtonEdit});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelFunction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAddOnlineCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddOnlineCourseActionPerformed
        // TODO add your handling code here:

        GUI_AddOnlineCourse.main(null);
        this.dispose();
    }//GEN-LAST:event_ButtonAddOnlineCourseActionPerformed

    private void DataTable_CourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataTable_CourseMouseClicked
        // TODO add your handling code here:
        pos = this.DataTable_Course.getSelectedRow();

    }//GEN-LAST:event_DataTable_CourseMouseClicked

    private void TextFieldSearch_courseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldSearch_courseKeyReleased
        // TODO add your handling code here:
        DefaultTableModel obj_course = (DefaultTableModel) DataTable_Course.getModel();
        TableRowSorter<DefaultTableModel> oj1_course = new TableRowSorter<>(obj_course);
        DataTable_Course.setRowSorter(oj1_course);
        oj1_course.setRowFilter(RowFilter.regexFilter(TextFieldSearch_course.getText()));
    }//GEN-LAST:event_TextFieldSearch_courseKeyReleased

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
        try {
            DTO_Course course = this.courses.get(DataTable_Course.getSelectedRow());
            if (course.getURL() != null) {
                GUI_UpdateOnlineCourse.main(course);
            } else {
                GUI_UpdateOnsiteCourse.main(course);
            }
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error Edit Course", "Message", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(GUI_Course.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonAddOnsiteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddOnsiteCourseActionPerformed
        // TODO add your handling code here:
        GUI_AddOnsiteCourse.main(null);
        this.dispose();
    }//GEN-LAST:event_ButtonAddOnsiteCourseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = DataTable_Course.getSelectedRow();
        if (row > -1) {
            try {
                new BUS_Course().Delete_course(this.courses.get(row));
                listCourse();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Delete course fail", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Course().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonAddOnlineCourse;
    public javax.swing.JButton ButtonAddOnsiteCourse;
    public javax.swing.JButton ButtonEdit;
    public javax.swing.JTable DataTable_Course;
    public javax.swing.JLabel LabelSearch;
    private javax.swing.JLabel LabelStatus_course;
    public javax.swing.JLabel LabelTitle;
    public javax.swing.JPanel PanelFunction;
    public javax.swing.JPanel PanelTable;
    public javax.swing.JPanel PanelTitle;
    public javax.swing.JTextField TextFieldSearch_course;
    public javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
