/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Duc Anh
 */
public class GUI_ChooseOption extends javax.swing.JFrame {

    private String[] args;

    /**
     * Creates new form GUI_ChooseOption
     */
    public GUI_ChooseOption() {
        initComponents();

        setLocationRelativeTo(null);
        // Close Form/Window
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int option = JOptionPane.showConfirmDialog(
                        GUI_ChooseOption.this,
                        "Bạn có chắc muốn đóng ứng dụng không?",
                        "Xác nhận đóng",
                        JOptionPane.YES_NO_OPTION
                );

                if (option == JOptionPane.YES_OPTION) {
                    // Thực hiện các thao tác cần thiết trước khi đóng ứng dụng
                    // Ví dụ: Lưu dữ liệu, đóng kết nối, v.v.

                    // Đóng JFrame
                    dispose();

                    // (Optional) Kết thúc ứng dụng
                    System.exit(0);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonChooseOptionDepartmentManagement3 = new javax.swing.JButton();
        PanelTitle = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        PanelOption = new javax.swing.JPanel();
        ButtonChooseOptionCourseInstructorManagement = new javax.swing.JButton();
        ButtonChooseOptionCourseManagement = new javax.swing.JButton();
        ButtonChooseOptionDepartmentManagement = new javax.swing.JButton();
        ButtonChooseOptionOfficeAssignmentManagement = new javax.swing.JButton();
        ButtonChooseOptionOnsiteCourseManagement = new javax.swing.JButton();
        ButtonChooseOptionPersonManagement = new javax.swing.JButton();
        ButtonChooseOptionStudentGradeManagement = new javax.swing.JButton();
        ButtonChooseOptionOnlineCourseManagement = new javax.swing.JButton();
        btnResigeterCourse = new javax.swing.JButton();

        ButtonChooseOptionDepartmentManagement3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ButtonChooseOptionDepartmentManagement3.setText("Department Management");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        LabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitle.setText("HOME");

        javax.swing.GroupLayout PanelTitleLayout = new javax.swing.GroupLayout(PanelTitle);
        PanelTitle.setLayout(PanelTitleLayout);
        PanelTitleLayout.setHorizontalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTitleLayout.setVerticalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        ButtonChooseOptionCourseInstructorManagement.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ButtonChooseOptionCourseInstructorManagement.setText("Course Instructor");
        ButtonChooseOptionCourseInstructorManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseOptionCourseInstructorManagementActionPerformed(evt);
            }
        });

        ButtonChooseOptionCourseManagement.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ButtonChooseOptionCourseManagement.setText("Course");
        ButtonChooseOptionCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseOptionCourseManagementActionPerformed(evt);
            }
        });

        ButtonChooseOptionDepartmentManagement.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ButtonChooseOptionDepartmentManagement.setText("Department ");
        ButtonChooseOptionDepartmentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseOptionDepartmentManagementActionPerformed(evt);
            }
        });

        ButtonChooseOptionOfficeAssignmentManagement.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ButtonChooseOptionOfficeAssignmentManagement.setText(" Office Assignment");
        ButtonChooseOptionOfficeAssignmentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseOptionOfficeAssignmentManagementActionPerformed(evt);
            }
        });

        ButtonChooseOptionOnsiteCourseManagement.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ButtonChooseOptionOnsiteCourseManagement.setText("Onsite Course ");
        ButtonChooseOptionOnsiteCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseOptionOnsiteCourseManagementActionPerformed(evt);
            }
        });

        ButtonChooseOptionPersonManagement.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ButtonChooseOptionPersonManagement.setText("Person");
        ButtonChooseOptionPersonManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseOptionPersonManagementActionPerformed(evt);
            }
        });

        ButtonChooseOptionStudentGradeManagement.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ButtonChooseOptionStudentGradeManagement.setText("Student Grade");
        ButtonChooseOptionStudentGradeManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseOptionStudentGradeManagementActionPerformed(evt);
            }
        });

        ButtonChooseOptionOnlineCourseManagement.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        ButtonChooseOptionOnlineCourseManagement.setText("Online Course");
        ButtonChooseOptionOnlineCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChooseOptionOnlineCourseManagementActionPerformed(evt);
            }
        });

        btnResigeterCourse.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnResigeterCourse.setText("Register Course");
        btnResigeterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResigeterCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOptionLayout = new javax.swing.GroupLayout(PanelOption);
        PanelOption.setLayout(PanelOptionLayout);
        PanelOptionLayout.setHorizontalGroup(
            PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ButtonChooseOptionPersonManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(ButtonChooseOptionOfficeAssignmentManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(ButtonChooseOptionCourseManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonChooseOptionCourseInstructorManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(ButtonChooseOptionStudentGradeManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(ButtonChooseOptionOnlineCourseManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonChooseOptionDepartmentManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(ButtonChooseOptionOnsiteCourseManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResigeterCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelOptionLayout.setVerticalGroup(
            PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonChooseOptionCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonChooseOptionCourseInstructorManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResigeterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonChooseOptionOfficeAssignmentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonChooseOptionOnlineCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonChooseOptionOnsiteCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(PanelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonChooseOptionPersonManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonChooseOptionStudentGradeManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonChooseOptionDepartmentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonChooseOptionCourseManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseOptionCourseManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI_Course.main(args);
    }//GEN-LAST:event_ButtonChooseOptionCourseManagementActionPerformed

    private void ButtonChooseOptionCourseInstructorManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseOptionCourseInstructorManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI_CourseInstructor.main(args);
    }//GEN-LAST:event_ButtonChooseOptionCourseInstructorManagementActionPerformed

    private void ButtonChooseOptionDepartmentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseOptionDepartmentManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI_Department.main(args);
    }//GEN-LAST:event_ButtonChooseOptionDepartmentManagementActionPerformed

    private void ButtonChooseOptionOfficeAssignmentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseOptionOfficeAssignmentManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI_OfficeAssignment.main(args);
    }//GEN-LAST:event_ButtonChooseOptionOfficeAssignmentManagementActionPerformed

    private void ButtonChooseOptionPersonManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseOptionPersonManagementActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        GUI_Person.main(args);
    }//GEN-LAST:event_ButtonChooseOptionPersonManagementActionPerformed

    private void ButtonChooseOptionStudentGradeManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseOptionStudentGradeManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI_StudentGrade.main(args);
    }//GEN-LAST:event_ButtonChooseOptionStudentGradeManagementActionPerformed

    private void btnResigeterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResigeterCourseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI_RegisterCourse.main(args);
    }//GEN-LAST:event_btnResigeterCourseActionPerformed

    private void ButtonChooseOptionOnlineCourseManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseOptionOnlineCourseManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI_OnlineCourse.main(args);
    }//GEN-LAST:event_ButtonChooseOptionOnlineCourseManagementActionPerformed

    private void ButtonChooseOptionOnsiteCourseManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChooseOptionOnsiteCourseManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        GUI_OnsiteCourse.main(args);
    }//GEN-LAST:event_ButtonChooseOptionOnsiteCourseManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ChooseOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ChooseOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ChooseOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ChooseOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ChooseOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonChooseOptionCourseInstructorManagement;
    public javax.swing.JButton ButtonChooseOptionCourseManagement;
    public javax.swing.JButton ButtonChooseOptionDepartmentManagement;
    public javax.swing.JButton ButtonChooseOptionDepartmentManagement3;
    public javax.swing.JButton ButtonChooseOptionOfficeAssignmentManagement;
    public javax.swing.JButton ButtonChooseOptionOnlineCourseManagement;
    public javax.swing.JButton ButtonChooseOptionOnsiteCourseManagement;
    public javax.swing.JButton ButtonChooseOptionPersonManagement;
    public javax.swing.JButton ButtonChooseOptionStudentGradeManagement;
    public javax.swing.JLabel LabelTitle;
    public javax.swing.JPanel PanelOption;
    public javax.swing.JPanel PanelTitle;
    public javax.swing.JButton btnResigeterCourse;
    // End of variables declaration//GEN-END:variables
}
